package com.kishore.payments.core.instruction;

import com.kishore.payments.core.state.InstructionState;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.PostLoad;
import jakarta.persistence.PostPersist;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import jakarta.persistence.Version;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.springframework.data.domain.Persistable;

/**
 * Mirrors core.payment_instruction. state_version is mapped as a JPA
 * {@code @Version}: Hibernate issues every update as
 * {@code WHERE instruction_id = ? AND state_version = ?} and throws an
 * optimistic-locking exception on a zero-row update, which is exactly the
 * database-arbitrated concurrency guard .notes/ARCHITECTURE.md describes.
 *
 * <p>Implements {@link Persistable} because instruction_id is assigned by
 * application code, not generated by the database: without this, Spring Data
 * JPA's default "is the id null?" newness check would treat every brand-new
 * instruction as already persisted and issue a merge (a wasted SELECT before
 * every insert) instead of a plain insert.
 */
@Entity
@Table(name = "payment_instruction", schema = "core")
public class PaymentInstructionEntity implements Persistable<UUID> {

    @Id
    @Column(name = "instruction_id")
    private UUID instructionId;

    @Column(name = "raw_message_id", nullable = false)
    private UUID rawMessageId;

    @Column(name = "uetr", nullable = false, unique = true)
    private UUID uetr;

    @Column(name = "end_to_end_id", nullable = false)
    private String endToEndId;

    @Column(name = "instruction_id_ext")
    private String instructionIdExt;

    @Enumerated(EnumType.STRING)
    @Column(name = "state", nullable = false)
    private InstructionState state;

    @Version
    @Column(name = "state_version", nullable = false)
    private Integer stateVersion;

    @Column(name = "debtor_name", nullable = false)
    private String debtorName;

    @Column(name = "debtor_account", nullable = false)
    private String debtorAccount;

    @Column(name = "debtor_agent_bic", nullable = false)
    private String debtorAgentBic;

    @Column(name = "creditor_name", nullable = false)
    private String creditorName;

    @Column(name = "creditor_account", nullable = false)
    private String creditorAccount;

    @Column(name = "creditor_agent_bic", nullable = false)
    private String creditorAgentBic;

    @Column(name = "amount", nullable = false)
    private BigDecimal amount;

    @Column(name = "currency", nullable = false)
    private String currency;

    @Column(name = "charge_bearer")
    private String chargeBearer;

    @Column(name = "requested_exec_date", nullable = false)
    private LocalDate requestedExecDate;

    @Column(name = "value_date")
    private LocalDate valueDate;

    @Column(name = "settlement_date")
    private LocalDate settlementDate;

    @Column(name = "selected_rail")
    private String selectedRail;

    @Column(name = "correspondent_bic")
    private String correspondentBic;

    @Column(name = "nostro_account")
    private String nostroAccount;

    @Column(name = "refdata_version")
    private Long refdataVersion;

    @Column(name = "created_at", insertable = false, updatable = false)
    private OffsetDateTime createdAt;

    @Column(name = "updated_at")
    private OffsetDateTime updatedAt;

    @Transient
    private boolean isNew = true;

    protected PaymentInstructionEntity() {
        // JPA
    }

    public PaymentInstructionEntity(
            UUID instructionId,
            UUID rawMessageId,
            UUID uetr,
            String endToEndId,
            String instructionIdExt,
            String debtorName,
            String debtorAccount,
            String debtorAgentBic,
            String creditorName,
            String creditorAccount,
            String creditorAgentBic,
            BigDecimal amount,
            String currency,
            String chargeBearer,
            LocalDate requestedExecDate) {
        this.instructionId = instructionId;
        this.rawMessageId = rawMessageId;
        this.uetr = uetr;
        this.endToEndId = endToEndId;
        this.instructionIdExt = instructionIdExt;
        this.state = InstructionState.RECEIVED;
        // Seeded to 1 to line up with the seed instruction_event's
        // sequence_no = 1 (see PaymentInstructionWriter): both numbers move
        // together by construction, one increment per transition. Hibernate
        // only auto-seeds @Version fields left null; assigning it here means
        // this value is what actually gets inserted.
        this.stateVersion = 1;
        this.debtorName = debtorName;
        this.debtorAccount = debtorAccount;
        this.debtorAgentBic = debtorAgentBic;
        this.creditorName = creditorName;
        this.creditorAccount = creditorAccount;
        this.creditorAgentBic = creditorAgentBic;
        this.amount = amount;
        this.currency = currency;
        this.chargeBearer = chargeBearer;
        this.requestedExecDate = requestedExecDate;
        // updated_at has no DB default that applies here: it's NOT NULL with
        // DEFAULT now(), but that default only fires when the column is
        // omitted from the INSERT entirely, and Hibernate always includes a
        // mapped, non-insertable=false column. Left unset, this field is
        // null in Java and the insert fails NOT NULL rather than falling
        // back to the default.
        this.updatedAt = OffsetDateTime.now();
    }

    @Override
    public UUID getId() {
        return instructionId;
    }

    @Override
    public boolean isNew() {
        return isNew;
    }

    @PostLoad
    @PostPersist
    void markNotNew() {
        isNew = false;
    }

    public UUID getInstructionId() {
        return instructionId;
    }

    public UUID getRawMessageId() {
        return rawMessageId;
    }

    public UUID getUetr() {
        return uetr;
    }

    public String getEndToEndId() {
        return endToEndId;
    }

    public String getInstructionIdExt() {
        return instructionIdExt;
    }

    public InstructionState getState() {
        return state;
    }

    public void setState(InstructionState state) {
        this.state = state;
    }

    public Integer getStateVersion() {
        return stateVersion;
    }

    public String getDebtorName() {
        return debtorName;
    }

    public String getDebtorAccount() {
        return debtorAccount;
    }

    public String getDebtorAgentBic() {
        return debtorAgentBic;
    }

    public String getCreditorName() {
        return creditorName;
    }

    public String getCreditorAccount() {
        return creditorAccount;
    }

    public String getCreditorAgentBic() {
        return creditorAgentBic;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public String getCurrency() {
        return currency;
    }

    public String getChargeBearer() {
        return chargeBearer;
    }

    public void setChargeBearer(String chargeBearer) {
        this.chargeBearer = chargeBearer;
    }

    public LocalDate getRequestedExecDate() {
        return requestedExecDate;
    }

    public LocalDate getValueDate() {
        return valueDate;
    }

    public void setValueDate(LocalDate valueDate) {
        this.valueDate = valueDate;
    }

    public LocalDate getSettlementDate() {
        return settlementDate;
    }

    public void setSettlementDate(LocalDate settlementDate) {
        this.settlementDate = settlementDate;
    }

    public String getSelectedRail() {
        return selectedRail;
    }

    public void setSelectedRail(String selectedRail) {
        this.selectedRail = selectedRail;
    }

    public String getCorrespondentBic() {
        return correspondentBic;
    }

    public void setCorrespondentBic(String correspondentBic) {
        this.correspondentBic = correspondentBic;
    }

    public String getNostroAccount() {
        return nostroAccount;
    }

    public void setNostroAccount(String nostroAccount) {
        this.nostroAccount = nostroAccount;
    }

    public Long getRefdataVersion() {
        return refdataVersion;
    }

    public void setRefdataVersion(Long refdataVersion) {
        this.refdataVersion = refdataVersion;
    }

    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}
