package com.kishore.payments.exception.cases;

import com.kishore.payments.core.domain.FailureStage;
import com.kishore.payments.core.domain.Repairability;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.PostLoad;
import jakarta.persistence.PostPersist;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.springframework.data.domain.Persistable;

/**
 * Mirrors exceptions.exception_case. Implements {@link Persistable} for the
 * same reason {@code PaymentInstructionEntity} does: case_id is assigned by
 * application code, not generated by the database, so Spring Data's default
 * newness check (is the id null?) would otherwise treat every new case as
 * already persisted and issue a wasted merge instead of a plain insert.
 *
 * <p>No {@code classifierCode}/{@code classifierConf}/{@code
 * classifierAccepted} mapping: those columns exist in the schema for Phase
 * 11's not-yet-built classifier (.notes/ARCHITECTURE.md §10), and mapping
 * them here with nothing to ever set them would be exactly the kind of stub
 * the phase brief says to leave out.
 */
@Entity
@Table(name = "exception_case", schema = "exceptions")
public class ExceptionCaseEntity implements Persistable<UUID> {

    @Id
    @Column(name = "case_id")
    private UUID caseId;

    @Column(name = "instruction_id", nullable = false)
    private UUID instructionId;

    @Column(name = "opened_at", insertable = false, updatable = false)
    private OffsetDateTime openedAt;

    @Column(name = "closed_at")
    private OffsetDateTime closedAt;

    @Enumerated(EnumType.STRING)
    @Column(name = "case_type", nullable = false)
    private CaseType caseType;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private CaseStatus status;

    @Enumerated(EnumType.STRING)
    @Column(name = "failure_stage", nullable = false)
    private FailureStage failureStage;

    @Column(name = "reason_code")
    private String reasonCode;

    @Column(name = "reason_detail")
    private String reasonDetail;

    @Enumerated(EnumType.STRING)
    @Column(name = "repairability", nullable = false)
    private Repairability repairability;

    @Column(name = "assigned_to")
    private String assignedTo;

    @Enumerated(EnumType.STRING)
    @Column(name = "resolution")
    private Resolution resolution;

    @Column(name = "repair_attempts", nullable = false)
    private int repairAttempts;

    @Column(name = "justification")
    private String justification;

    @Transient
    private boolean isNew = true;

    protected ExceptionCaseEntity() {
        // JPA
    }

    public ExceptionCaseEntity(
            UUID caseId,
            UUID instructionId,
            CaseType caseType,
            FailureStage failureStage,
            String reasonCode,
            String reasonDetail,
            Repairability repairability,
            int startingRepairAttempts) {
        this.caseId = caseId;
        this.instructionId = instructionId;
        this.caseType = caseType;
        this.status = CaseStatus.OPEN;
        this.failureStage = failureStage;
        this.reasonCode = reasonCode;
        this.reasonDetail = reasonDetail;
        this.repairability = repairability;
        this.repairAttempts = startingRepairAttempts;
    }

    @Override
    public UUID getId() {
        return caseId;
    }

    @Override
    public boolean isNew() {
        return isNew;
    }

    @PostLoad
    @PostPersist
    void markNotNew() {
        isNew = false;
    }

    public UUID getCaseId() {
        return caseId;
    }

    public UUID getInstructionId() {
        return instructionId;
    }

    public OffsetDateTime getOpenedAt() {
        return openedAt;
    }

    public OffsetDateTime getClosedAt() {
        return closedAt;
    }

    public CaseType getCaseType() {
        return caseType;
    }

    public CaseStatus getStatus() {
        return status;
    }

    public void setStatus(CaseStatus status) {
        this.status = status;
    }

    public FailureStage getFailureStage() {
        return failureStage;
    }

    public void setFailureStage(FailureStage failureStage) {
        this.failureStage = failureStage;
    }

    public String getReasonCode() {
        return reasonCode;
    }

    public void setReasonCode(String reasonCode) {
        this.reasonCode = reasonCode;
    }

    public String getReasonDetail() {
        return reasonDetail;
    }

    public void setReasonDetail(String reasonDetail) {
        this.reasonDetail = reasonDetail;
    }

    public Repairability getRepairability() {
        return repairability;
    }

    public void setRepairability(Repairability repairability) {
        this.repairability = repairability;
    }

    public String getAssignedTo() {
        return assignedTo;
    }

    public void setAssignedTo(String assignedTo) {
        this.assignedTo = assignedTo;
    }

    public Resolution getResolution() {
        return resolution;
    }

    public void setResolution(Resolution resolution) {
        this.resolution = resolution;
    }

    public int getRepairAttempts() {
        return repairAttempts;
    }

    public void setRepairAttempts(int repairAttempts) {
        this.repairAttempts = repairAttempts;
    }

    public String getJustification() {
        return justification;
    }

    public void setJustification(String justification) {
        this.justification = justification;
    }

    public void setClosedAt(OffsetDateTime closedAt) {
        this.closedAt = closedAt;
    }
}
